name: cabal

on:
  push:
    branches:
      - 'dino'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.6", "8.8", "8.10"]
        cabal: ["3.2"]
        cache-version: ["2020-10-18"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache cabal
      uses: actions/cache@v2
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cache-version }}-cabal
        
    - name: Install libralies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-image-dev

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --disable-optimization --write-ghc-environment-files=always -j2
        cabal build --only-dependencies

    - name: Build
      run: |
        cabal build
        cabal install all:exes --overwrite-policy=always